# Generated by Django 5.2.6 on 2025-10-20 17:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={},
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='notes',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Transport', 'Transport'), ('Bills', 'Bills'), ('Shopping', 'Shopping'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='expense',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
